package com.rohit.app.core.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@EqualsAndHashCode
@ToString
@DynamoDBTable(tableName = "FirstSampleDDBTable")
public class User {

    @Getter @Setter @DynamoDBAttribute(attributeName = "FirstName")
    private String firstName;
    @Getter @Setter @DynamoDBAttribute(attributeName = "LastName")
    private String lastName;
    @Getter @Setter @DynamoDBAttribute(attributeName = "PreFix")
    private String preFix;
    @Getter @Setter @DynamoDBAttribute(attributeName = "ContactInformation")
    private ContactInformation contactInformation;
    @Getter @Setter @DynamoDBAttribute(attributeName = "Address")
    private Address address;
    @Getter @DynamoDBAutoGeneratedKey @DynamoDBHashKey(attributeName = "userId")
    private String userId;

}
